package sample.backend.persistence.database.postgresql.table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@NoArgsConstructor
@Data
@AllArgsConstructor
@Builder
public class DbOperator {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.operator_id
     *
     * @mbg.generated
     */
    private Integer operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operator.operator_name
     *
     * @mbg.generated
     */
    private String operatorName;
}